# Task 10: Introduction to NumPy (arrays, basic operations)

## Introduction to NumPy

NumPy is a powerful library for numerical computing in Python. It provides support for large multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on these arrays efficiently.

### Basic NumPy Operations

Here are some basic operations you can perform with NumPy:

1. **Creating Arrays**:
    ```python

    # Create a 1D array
    arr1 = np.array([1, 2, 3, 4, 5])
    
    # Create a 2D array
    arr2 = np.array([[1, 2, 3], [4, 5, 6]])
    ```

2. **Array Shape**:
    ```python
    # Get the shape of the array
    arr1.shape  # Output: (5,)
    arr2.shape  # Output: (2, 3)
    ```

3. **Array Indexing and Slicing**:
    ```python
    # Indexing
    element = arr1[0]  # Output: 1
    
    # Slicing
    sub_array = arr2[:, 1:3]  # Output: array([[2, 3], [5, 6]])
    ```

4. **Basic Arithmetic Operations**:
    ```python
    # Element-wise addition
    arr_sum = arr1 + 5  # Output: array([ 6,  7,  8,  9, 10])
    
    # Element-wise multiplication
    arr_mul = arr1 * 2  # Output: array([ 2,  4,  6,  8, 10])
    ```

In [17]:
# importing Numpy
import numpy as np

In [18]:
#Task 1: Create a 1D NumPy array containing the integers from 0 to 9.

array_1d = np.arange(10)
print("1D array:", array_1d)

1D array: [0 1 2 3 4 5 6 7 8 9]


In [19]:
#Task 2: Create a 2D NumPy array (3x3) containing random integers between 1 and 20.

array_2d = np.random.randint(1, 21, size=(3, 3))
print("2D array:\n", array_2d)

2D array:
 [[10 10 12]
 [17 12 18]
 [ 4 17 17]]


In [20]:
#Task 3: Create a 3D NumPy array with dimensions (2, 3, 4) filled with ones.

array_3d = np.ones((2, 3, 4))
print("3D array:\n", array_3d)

3D array:
 [[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [21]:
#Task 4: Add two 1D arrays element-wise.

array_1 = np.array([1, 2, 3])
array_2 = np.array([4, 5, 6])
added_arrays = np.add(array_1, array_2)
print("Added 1D arrays:", added_arrays)

Added 1D arrays: [5 7 9]


In [22]:
#Task 5: Multiply two 2D arrays element-wise.

array_2d_1 = np.random.randint(1, 10, size=(3, 3))
array_2d_2 = np.random.randint(1, 10, size=(3, 3))
multiplied_arrays = np.multiply(array_2d_1, array_2d_2)
print("2D arrays 1:\n", array_2d_1)
print("2D arrays 2:\n", array_2d_2)
print("Multiplied 2D arrays:\n", multiplied_arrays)

2D arrays 1:
 [[8 3 7]
 [9 2 8]
 [2 2 1]]
2D arrays 2:
 [[1 9 3]
 [7 1 7]
 [9 1 2]]
Multiplied 2D arrays:
 [[ 8 27 21]
 [63  2 56]
 [18  2  2]]


In [23]:
#Task 6: Calculate the dot product of two matrices.

matrix_1 = np.random.randint(1, 10, size=(3, 3))
matrix_2 = np.random.randint(1, 10, size=(3, 3))
dot_product = np.dot(matrix_1, matrix_2)
print("Matrix 1:\n", matrix_1)
print("Matrix 2:\n", matrix_2)
print("Dot product of matrices:\n", dot_product)

Matrix 1:
 [[5 8 3]
 [8 6 6]
 [1 1 5]]
Matrix 2:
 [[4 9 6]
 [6 8 8]
 [6 2 2]]
Dot product of matrices:
 [[ 86 115 100]
 [104 132 108]
 [ 40  27  24]]


In [24]:
#Task 7: Calculate the mean, median, and standard deviation of a 1D array.

array_for_stats = np.random.randint(1, 100, size=10)
mean = np.mean(array_for_stats)
median = np.median(array_for_stats)
std_dev = np.std(array_for_stats)
print("Array for stats:", array_for_stats)
print("Mean:", mean)
print("Median:", median)
print("Standard Deviation:", std_dev)

Array for stats: [96 63 77 95 33 83 12 92 65 65]
Mean: 68.1
Median: 71.0
Standard Deviation: 26.074700381787707


In [25]:
#Task 8: Find the maximum and minimum values in a 2D array.

array_2d_for_min_max = np.random.randint(1, 100, size=(5, 5))
max_value = np.max(array_2d_for_min_max)
min_value = np.min(array_2d_for_min_max)
print("2D array for min and max:\n", array_2d_for_min_max)
print("Maximum value:", max_value)
print("Minimum value:", min_value)

2D array for min and max:
 [[24 10 34 33 67]
 [23 42 47 62 38]
 [59 52 55 54 18]
 [27 60 41 91 77]
 [17 67 60 16 93]]
Maximum value: 93
Minimum value: 10


In [26]:
#Task 9: Generate an array of 1000 random numbers from a normal distribution with a mean of 0 and a standard deviation of 1.

normal_dist_array = np.random.normal(0, 1, 1000)
print("Array from normal distribution:\n", normal_dist_array)

Array from normal distribution:
 [ 0.45177377 -0.18261142  0.3974868  -0.21736839  1.09053737  0.39121928
  1.6445071   0.82597352 -1.00093654  0.45803277 -2.10747819 -1.03918694
  0.46671107  0.54181964  0.14249985  2.08828211 -2.06197227  0.2978908
 -0.66676732 -0.06991395  0.28058198  0.14542624 -0.76115997  0.59315635
 -0.80649357  0.11636172  0.76621074  1.46590491 -0.87062607 -2.29282396
  0.51095941  0.66955903 -1.22134497  0.23111857 -0.58396756 -0.11542582
 -0.90835051 -0.79882643 -2.98279471 -0.06546687  0.948759    0.52407521
  1.60902166 -0.95419842  1.43298803  2.05374152 -0.11110806 -0.38510575
 -0.98889579  1.36224203 -0.13763057  0.04421292  0.15233211 -0.0093667
 -0.53571888 -1.27245107 -0.86590139 -0.79430648  0.47822013 -0.40601889
 -1.86074629 -1.0878368   0.16152865  0.31484892  3.46927081  0.23886454
 -0.36728056 -0.53254209  1.07507814  0.09529654  1.25020355  0.08252473
  1.27999346  0.06137527 -1.6500261   2.12243371 -1.38607682  0.66511297
  0.02869305 -0.3363

In [27]:
#Task 10: Create a 2D array of shape (5, 5) with random integers from a uniform distribution between 10 and 50.

uniform_dist_array = np.random.randint(10, 51, size=(5, 5))
print("2D array from uniform distribution:\n", uniform_dist_array)

2D array from uniform distribution:
 [[36 18 41 36 48]
 [32 13 17 20 40]
 [20 20 29 30 12]
 [47 35 46 21 45]
 [48 12 41 41 37]]


In [28]:
#Task 11: Calculate the cumulative sum of a 1D array.

array_for_cumsum = np.random.randint(1, 10, size=10)
cumulative_sum = np.cumsum(array_for_cumsum)
print("Array for cumulative sum:", array_for_cumsum)
print("Cumulative sum:", cumulative_sum)

Array for cumulative sum: [9 1 6 2 9 8 1 4 6 4]
Cumulative sum: [ 9 10 16 18 27 35 36 40 46 50]


In [29]:
#Task 12: Compute the correlation coefficient matrix of a 2D array.

array_2d_for_corr = np.random.rand(5, 5)
correlation_matrix = np.corrcoef(array_2d_for_corr)
print("2D array for correlation matrix:\n", array_2d_for_corr)
print("Correlation coefficient matrix:\n", correlation_matrix)

2D array for correlation matrix:
 [[0.12131682 0.70748411 0.44065638 0.5608018  0.43795814]
 [0.75399425 0.24760753 0.81494612 0.05350723 0.57505427]
 [0.12750664 0.94672773 0.16477022 0.360238   0.42880788]
 [0.71561748 0.8598854  0.07862676 0.15577315 0.51249357]
 [0.90064548 0.45190934 0.99820531 0.63928687 0.28014094]]
Correlation coefficient matrix:
 [[ 1.         -0.70985952  0.80270447 -0.04038193 -0.51454175]
 [-0.70985952  1.         -0.60533354 -0.03588191  0.50862114]
 [ 0.80270447 -0.60533354  1.          0.56289722 -0.68259668]
 [-0.04038193 -0.03588191  0.56289722  1.         -0.40082542]
 [-0.51454175  0.50862114 -0.68259668 -0.40082542  1.        ]]


In [30]:
#Task 13: Simulate rolling a six-sided die 1000 times and count the frequency of each outcome.

dice_rolls = np.random.randint(1, 7, size=1000)
unique, counts = np.unique(dice_rolls, return_counts=True)
frequency = dict(zip(unique, counts))
print("Frequency of dice rolls:", frequency)

Frequency of dice rolls: {1: 153, 2: 155, 3: 193, 4: 180, 5: 160, 6: 159}
