# <b><p style="background-color: #ff6200; font-family:calibri; color:white; font-size:100%; font-family:Verdana; text-align:center; border-radius:15px 50px;">Task 21-> Linear algebra and calculus in NumPy</p>

Linear Algebra and Calculus are foundational branches of mathematics essential in various fields, including machine learning, physics, engineering, and economics. Each discipline plays a crucial role in modeling and solving real-world problems.

### Linear Algebra

Linear Algebra deals with linear equations, vectors, matrices, and their properties. Key concepts include:

- **Vectors**: Quantities with direction and magnitude.
- **Matrices**: Rectangular arrays of numbers.
- **Linear Transformations**: Functions that map vectors to new vectors while preserving linearity.

### Calculus

Calculus focuses on the study of change and motion. It includes:

- **Differentiation**: Finding rates of change or slopes of curves.
- **Integration**: Calculating areas under curves and solving accumulation problems.
- **Limits**: Understanding behavior of functions as inputs approach certain values.


### Linear Algebra Tasks

1. [Matrix Creation and Manipulation](#1)
    - Create various types of matrices (zero matrix, identity matrix, random matrix).
    - Perform basic matrix operations (addition, subtraction, multiplication).
    - Transpose a matrix and find the determinant and inverse of a matrix.
2. [Solving Linear Equations](#2)
    - Use NumPy to solve a system of linear equations.
    - Implement matrix factorization methods (LU decomposition, QR decomposition).
3. [Eigenvalues and Eigenvectors](#3)
    - Calculate the eigenvalues and eigenvectors of a given matrix.
    - Verify the results by reconstructing the original matrix.
4. [Vector Operations](#4)
    - Perform basic vector operations (addition, dot product, cross product).
    - Normalize a vector and compute vector norms.
5. [Matrix Decomposition](#5)
    - Understand and implement Principal Component Analysis (PCA) using SVD.

### Calculus Tasks
1. [Numerical Differentiation](#01)
    - Use NumPy to compute the numerical derivative of a given function.
    - Implement forward, backward, and central difference methods for differentiation.
2. [Numerical Integration](#01)
    - Use NumPy to compute the numerical integral of a given function.
    - Implement the trapezoidal rule and Simpson's rule for integration.
3. [Partial Derivatives](#03)
    - Calculate partial derivatives of multivariable functions using NumPy.
    - Verify results by comparing with analytical solutions.
4. [Optimization](#04)
    - Use NumPy to solve optimization problems with constraints.


In [1]:
import numpy as np

# <b><span style='color:#ff6200'> Linear Algerbra Tasks</span>

<a id=1></a>
## <b><span style='color:#fcc36d'>1| Matrix Creation and Manipulation</span>

#### Different matrices

In [7]:
zero_matrix = np.zeros((3, 3))
print("Zero Matrix:\n", zero_matrix)

ones_matrix = np.ones((3, 4))
print("\nOnes Matrix:\n", ones_matrix)

identity_matrix = np.eye(3)
print("\nIdentity Matrix:\n", identity_matrix)

random_matrix = np.random.rand(3, 3)
print("\nRandom Matrix:\n", random_matrix)

Zero Matrix:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Ones Matrix:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Random Matrix:
 [[0.02478667 0.82613451 0.99650544]
 [0.13868779 0.9622598  0.39773977]
 [0.50888008 0.82742832 0.34333914]]


#### Basic Matrix Operations

In [28]:
matrix_a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matrix_b = np.array([[3, 8, 7], [6, 6, 4], [8, 2, 9]])

matrix_addition = matrix_a + matrix_b
print("\nMatrix Addition:\n", matrix_addition)


Matrix Addition:
 [[ 4 10 10]
 [10 11 10]
 [15 10 18]]


In [29]:
matrix_subtraction = matrix_a - matrix_b
print("\nMatrix Subtraction:\n", matrix_subtraction)


Matrix Subtraction:
 [[-2 -6 -4]
 [-2 -1  2]
 [-1  6  0]]


In [30]:
matrix_multiplication = np.dot(matrix_a, matrix_b)
print("\nMatrix Multiplication:\n", matrix_multiplication)


Matrix Multiplication:
 [[ 39  26  42]
 [ 90  74 102]
 [141 122 162]]


#### Transpose

In [31]:
matrix_transpose = np.transpose(matrix_a)
print("\nTranspose of Matrix A:\n", matrix_transpose)


Transpose of Matrix A:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]


In [32]:
matrix_transpose = matrix_a.T
print("\nTranspose of Matrix A:\n", matrix_transpose)


Transpose of Matrix A:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]


#### Determinant

In [33]:
matrix_determinant = np.linalg.det(matrix_b)
print("\nDeterminant of Matrix C:\n", matrix_determinant)


Determinant of Matrix C:
 -289.99999999999994


#### Inverse of matrix

In [37]:
try:
    matrix_inverse = np.linalg.inv(matrix_b)
    print("\nInverse of Matrix b:\n", matrix_inverse)
except np.linalg.LinAlgError:
    print("\nMatrix is singular and cannot be inverted.")


Inverse of Matrix b:
 [[-0.15862069  0.2         0.03448276]
 [ 0.07586207  0.1        -0.10344828]
 [ 0.12413793 -0.2         0.10344828]]


<a id=2></a>
## <b><span style='color:#fcc36d'>2| Solving Linear Equations</span>

In [47]:
# Solving a System of Linear Equations
# Example: 2x + 3y = 8
#          3x + 4y = 11

A = np.array([[4, 5], [8, 3]])
B = np.array([8, 11])

#### Using np to solve system of equations

In [48]:
solution = np.linalg.solve(A, B)
print("Solution to the system of linear equations:\n", solution)

Solution to the system of linear equations:
 [1.10714286 0.71428571]


#### LU Decomposition

In [49]:
from scipy.linalg import lu, qr

P, L, U = lu(A)
print("\nLU Decomposition:")
print("P (Permutation Matrix):\n", P)
print("L (Lower Triangular Matrix):\n", L)
print("U (Upper Triangular Matrix):\n", U)


LU Decomposition:
P (Permutation Matrix):
 [[0. 1.]
 [1. 0.]]
L (Lower Triangular Matrix):
 [[1.  0. ]
 [0.5 1. ]]
U (Upper Triangular Matrix):
 [[8.  3. ]
 [0.  3.5]]


#### QR Decomposition

In [53]:
Q, R = qr(A)
print("Q (Orthogonal Matrix):\n", Q)
print("\nR (Upper Triangular Matrix):\n", R)

Q (Orthogonal Matrix):
 [[-0.4472136  -0.89442719]
 [-0.89442719  0.4472136 ]]

R (Upper Triangular Matrix):
 [[-8.94427191 -4.91934955]
 [ 0.         -3.13049517]]


<a id=3></a>
## <b><span style='color:#fcc36d'>3| Eigenvalues and Eigenvectors</span>

Eigenvalues and eigenvectors are fundamental concepts in linear algebra, playing a crucial role in various applications such as stability analysis, vibration analysis, facial recognition, and more. Eigenvalues represent the factors by which the eigenvectors are scaled during a linear transformation represented by a matrix. Eigenvectors, on the other hand, are vectors that, when transformed by the matrix, change only in scale and not in direction. These concepts are not only theoretical but also have practical implications in fields like physics, computer science, and engineering.

In [56]:
A = np.array([[4, 2], [1, 3]])

eigenvalues, eigenvectors = np.linalg.eig(A)
print("Eigenvalues:\n", eigenvalues)
print("\nEigenvectors:\n", eigenvectors)

Eigenvalues:
 [5. 2.]

Eigenvectors:
 [[ 0.89442719 -0.70710678]
 [ 0.4472136   0.70710678]]


#### Reconstruction of oriinal matrix

In [58]:
reconstructed_matrix = np.dot(eigenvectors, np.dot(np.diag(eigenvalues), np.linalg.inv(eigenvectors)))
print("\nReconstructed Matrix:\n", reconstructed_matrix)


Reconstructed Matrix:
 [[4. 2.]
 [1. 3.]]


<a id=4></a>
## <b><span style='color:#fcc36d'>4| Vector Operations</span>

In [59]:
vector_a = np.array([1, 2, 3])
vector_b = np.array([4, 5, 6])

#### Basic Vector Operations

In [65]:
vector_addition = vector_a + vector_b
print("Vector Addition:\n", vector_addition)

Vector Addition:
 [5 7 9]


In [66]:
dot_product = np.dot(vector_a, vector_b)
print("Dot Product:\n", dot_product)

Dot Product:
 32


In [67]:
cross_product = np.cross(vector_a, vector_b)
print("Cross Product:\n", cross_product)

Cross Product:
 [-3  6 -3]


#### Vector Normalization

In [71]:
def normalize(vector):
    norm = np.linalg.norm(vector)
    return vector / norm

normalized_vector = normalize(vector_a)
print("\nNormalized Vector:\n", normalized_vector)


Normalized Vector:
 [0.26726124 0.53452248 0.80178373]


#### computing Norms

In [73]:
euclidean_norm = np.linalg.norm(vector_a)
print("Euclidean Norm (L2 Norm):\n", euclidean_norm)

manhattan_norm = np.linalg.norm(vector_a, ord=1)
print("\nManhattan Norm (L1 Norm):\n", manhattan_norm)

infinity_norm = np.linalg.norm(vector_a, ord=np.inf)
print("\nInfinity Norm (L-infinity Norm):\n", infinity_norm)

Euclidean Norm (L2 Norm):
 3.7416573867739413

Manhattan Norm (L1 Norm):
 6.0

Infinity Norm (L-infinity Norm):
 3.0


<a id=5></a>
## <b><span style='color:#fcc36d'>5| Matrix Decomposition</span> 

#### Principal Component Analysis (PCA)
Principal Component Analysis (PCA) is a powerful technique used for dimensionality reduction, data compression, and feature extraction. It helps in transforming a large set of variables into a smaller one that still contains most of the information in the large set. PCA can be implemented using Singular Value Decomposition (SVD), which is a method of decomposing a matrix into three other matrices.

#### Principal Component Analysis (PCA) using Singular Value Decomposition (SVD)
Steps to Implement PCA using SVD
- Standardize the Data: This step ensures that each feature has a mean of 0 and a standard deviation of 1.
- Compute the Covariance Matrix: This matrix describes the variance and covariance between different features in the dataset.
- Perform SVD: Decompose the covariance matrix using SVD to get the principal components.
- Select Principal Components: Choose the top 
𝑘
k principal components that capture the most variance.
- Transform the Data: Project the original data onto the selected principal components.

In [74]:
from sklearn.preprocessing import StandardScaler

def standardize_data(X):
    scaler = StandardScaler()
    X_standardized = scaler.fit_transform(X)
    return X_standardized

def compute_covariance_matrix(X):
    covariance_matrix = np.cov(X.T)
    return covariance_matrix

def perform_svd(covariance_matrix):
    U, S, Vt = np.linalg.svd(covariance_matrix)
    return U, S, Vt

def select_principal_components(U, num_components):
    principal_components = U[:, :num_components]
    return principal_components

def transform_data(X, principal_components):
    transformed_data = np.dot(X, principal_components)
    return transformed_data

def pca_using_svd(X, num_components):
    X_standardized = standardize_data(X)
    covariance_matrix = compute_covariance_matrix(X_standardized)
    U, S, Vt = perform_svd(covariance_matrix)
    principal_components = select_principal_components(U, num_components)
    X_pca = transform_data(X_standardized, principal_components)
    return X_pca, principal_components, S

X = np.array([[2.5, 2.4],
              [0.5, 0.7],
              [2.2, 2.9],
              [1.9, 2.2],
              [3.1, 3.0],
              [2.3, 2.7],
              [2.0, 1.6],
              [1.0, 1.1],
              [1.5, 1.6],
              [1.1, 0.9]])

num_components = 1
X_pca, principal_components, explained_variance = pca_using_svd(X, num_components)

print("Transformed Data:\n", X_pca)
print("\nPrincipal Components:\n", principal_components)
print("\nExplained Variance:\n", explained_variance)

Transformed Data:
 [[-1.08643242]
 [ 2.3089372 ]
 [-1.24191895]
 [-0.34078247]
 [-2.18429003]
 [-1.16073946]
 [ 0.09260467]
 [ 1.48210777]
 [ 0.56722643]
 [ 1.56328726]]

Principal Components:
 [[-0.70710678]
 [-0.70710678]]

Explained Variance:
 [2.13992141 0.08230081]


# <b><span style='color:#ff6200'> Calculus Tasks</span>

<a id=01></a>
## <b><span style='color:#fcc36d'>1| Numerical Differentiation</span>

Numerical derivations involve approximating derivatives of functions using numerical methods rather than analytic solutions. Common techniques include finite difference methods like forward, backward, and central differencing.

In [76]:
f = lambda x: np.sin(x)
x = np.pi / 4
h = 1e-5

forward_diff = (f(x + h) - f(x)) / h
print("Forward Difference Approximation:", forward_diff)

backward_diff = (f(x) - f(x - h)) / h
print("\nBackward Difference Approximation:", backward_diff)

central_diff = (f(x + h) - f(x - h)) / (2 * h)
print("\nCentral Difference Approximation:", central_diff)

Forward Difference Approximation: 0.7071032456340552

Backward Difference Approximation: 0.7071103167111125

Central Difference Approximation: 0.7071067811725839


<a id=02></a>
## <b><span style='color:#fcc36d'>2| Numerical Integration</span>

Numerical integration, or numerical integration, refers to techniques for approximating definite integrals of functions. Methods include trapezoidal rule, Simpson's rule, and Monte Carlo integration, which compute the area under curves or between points numerically.

In [78]:
def f(x):
    return np.sin(x)

def trapezoidal_rule(f, a, b, n):
    x = np.linspace(a, b, n+1)
    y = f(x)
    h = (b - a) / n
    integral = (h / 2) * (y[0] + 2 * np.sum(y[1:-1]) + y[-1])
    return integral

def simpsons_rule(f, a, b, n):
    if n % 2 == 1:
        n += 1  # Simpson's rule requires an even number of intervals
    x = np.linspace(a, b, n+1)
    y = f(x)
    h = (b - a) / n
    integral = (h / 3) * (y[0] + 4 * np.sum(y[1:-1:2]) + 2 * np.sum(y[2:-2:2]) + y[-1])
    return integral

a = 0  
b = np.pi  
n = 100  

trapezoidal_integral = trapezoidal_rule(f, a, b, n)
simpsons_integral = simpsons_rule(f, a, b, n)

print("Trapezoidal Rule Approximation:", trapezoidal_integral)
print("Simpson's Rule Approximation:", simpsons_integral)

exact_integral = -np.cos(b) + np.cos(a)
print("Exact Integral:", exact_integral)

Trapezoidal Rule Approximation: 1.9998355038874436
Simpson's Rule Approximation: 2.000000010824504
Exact Integral: 2.0


<a id=03></a>
## <b><span style='color:#fcc36d'>3| Partial Derivatives</span>

Partial integration, also known as integration by parts, is a technique used to evaluate definite or indefinite integrals of products of functions. It involves applying the product rule for differentiation in reverse to simplify the integration process.

In [79]:
def f(x, y):
    return x**2 + 2 * y

def partial_derivative_x(f, x, y, h):
    return (f(x + h, y) - f(x, y)) / h

def partial_derivative_y(f, x, y, h):
    return (f(x, y + h) - f(x, y)) / h

x = 1.0 
y = 2.0  
h = 1e-5  

partial_x_numeric = partial_derivative_x(f, x, y, h)
partial_y_numeric = partial_derivative_y(f, x, y, h)

partial_x_exact = 2 * x
partial_y_exact = 2

print("Partial derivative with respect to x (Numeric):", partial_x_numeric)
print("Partial derivative with respect to x (Exact):", partial_x_exact)
print("Partial derivative with respect to y (Numeric):", partial_y_numeric)
print("Partial derivative with respect to y (Exact):", partial_y_exact)

Partial derivative with respect to x (Numeric): 2.00001000001393
Partial derivative with respect to x (Exact): 2.0
Partial derivative with respect to y (Numeric): 2.0000000000131024
Partial derivative with respect to y (Exact): 2


<a id=04></a>
## <b><span style='color:#fcc36d'>4| Optimization</span>

In [81]:
from scipy.optimize import minimize

def objective(x):
    return x[0]**2 + x[1]**2

def constraint(x):
    return x[0] + x[1] - 1

x0 = np.array([0.5, 0.5])

bounds = ((None, None), (None, None))
constraint_eq = {'type': 'eq', 'fun': constraint}

result = minimize(objective, x0, bounds=bounds, constraints=constraint_eq)

print("Optimal solution:")
print("x:", result.x[0])
print("y:", result.x[1])
print("Objective value:", result.fun)

Optimal solution:
x: 0.5
y: 0.5
Objective value: 0.5
