# Task 11: NumPy advanced operations (indexing, slicing, broadcasting)

In [79]:
import numpy as np

## Indexing and Slicing

In [80]:
# Extract a 3x3 sub-array from a 2D array of shape (5, 5) starting from the element at position (1, 1)
array_2d =  np.random.randint(1, 50, size=(5, 5))
sub_array = array_2d[1:4, 1:4]
print("Original Array:\n", array_2d)
print("Extracted Sub-Array:\n", sub_array)

Original Array:
 [[12 11 41 26 12]
 [23  6 14 49 15]
 [ 4 28 29 13  7]
 [46 14 27 21  4]
 [37 14 19 49 35]]
Extracted Sub-Array:
 [[ 6 14 49]
 [28 29 13]
 [14 27 21]]


In [81]:
# From a 3D array of shape (4, 3, 2), extract all elements in the first two rows and all columns of the second slice along the third axis.
array_3d = np.arange(24).reshape(4, 3, 2)
extracted_elements = array_3d[:2, :, 1]
print("Original Array:\n", array_3d)
print("Extracted Elements:\n", extracted_elements)

Original Array:
 [[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]]
Extracted Elements:
 [[ 1  3  5]
 [ 7  9 11]]


In [82]:
# Given an array of integers, use fancy indexing to extract elements at positions [1, 3, 4, 7].

array_1d =  np.random.randint(1, 50, size=(10))
fancy_indexed_elements = array_1d[[1, 3, 4, 7]]
print ("Array: \n", array_1d)
print("Fancy Indexed Elements:\n",fancy_indexed_elements)

Array: 
 [16 16 36 24  5  9 17 27 11 13]
Fancy Indexed Elements:
 [16 24  5 27]


In [83]:
# Given a 2D array, use fancy indexing to select rows [0, 2, 3] and columns [1, 3]

array_2d = np.arange(25).reshape(5, 5)
fancy_indexed_sub_array = array_2d[[0, 2, 3], :][:, [1, 3]]
print ("Array: \n", array_2d)
print("Fancy Indexed selected Elements:\n",fancy_indexed_sub_array)

Array: 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
Fancy Indexed selected Elements:
 [[ 1  3]
 [11 13]
 [16 18]]


In [84]:
# From a 1D array of random integers, extract all elements that are greater than 10.

array_random = np.random.randint(1, 20, size=15)
elements_greater_than_10 = array_random[array_random > 10]
print ("Array: \n", array_random)
print("Elements greater than 10:\n",elements_greater_than_10)

Array: 
 [14  6  2 11  8 12  4 17 19  9 11 16  3  2 14]
Elements greater than 10:
 [14 11 12 17 19 11 16 14]


In [85]:
# Given a 2D array of shape (5, 5), replace all elements greater than 15 with the value 0.

array_2d = np.random.randint(1, 20, size=(5, 5))
print ("Array: \n", array_2d)
array_2d[array_2d > 15] = 0
print("Resulted Array:\n",array_2d)

Array: 
 [[11 13  6  8 15]
 [ 8  7 12 12  9]
 [14  7 15  5  3]
 [ 1  9  7  5 15]
 [ 9 11  3  1  4]]
Resulted Array:
 [[11 13  6  8 15]
 [ 8  7 12 12  9]
 [14  7 15  5  3]
 [ 1  9  7  5 15]
 [ 9 11  3  1  4]]


## Broadcasting

In [86]:
# Add a 1D array of shape (3,) to each row of a 2D array of shape (4, 3).

array_1d = np.array([1, 2, 3])
array_2d = np.random.randint(1, 10, size=(4, 3))
arrays_sum = array_2d + array_1d
print("Array 1:\n", array_1d)
print("Array 2:\n", array_2d)
print("Sum of Arrays:\n ",arrays_sum)

Array 1:
 [1 2 3]
Array 2:
 [[6 4 6]
 [3 7 1]
 [8 6 1]
 [8 6 4]]
Sum of Arrays:
  [[7 6 9]
 [4 9 4]
 [9 8 4]
 [9 8 7]]


In [87]:
# Multiply a 2D array of shape (3, 3) by a 1D array of shape (3,).

array_1d = np.array([1, 2, 3])
array_2d = np.random.randint(1, 10, size=(3, 3))
arrays_product = array_2d * array_1d
print("Array 1:\n", array_1d)
print("Array 2:\n", array_2d)
print("Product of arrays:\n", arrays_product)

Array 1:
 [1 2 3]
Array 2:
 [[5 7 5]
 [3 9 3]
 [7 9 1]]
Product of arrays:
 [[ 5 14 15]
 [ 3 18  9]
 [ 7 18  3]]


In [88]:
# Create two 2D arrays of shapes (3, 1) and (1, 4) respectively, and perform element-wise addition.

array_2d_1 = np.random.randint(1, 10, size=(3,1))
array_2d_2 = np.random.randint(1, 10, size=(1, 4))
element_wise_sum = array_2d_1 + array_2d_2
print("Array 1:\n", array_2d_1)
print("Array 2:\n", array_2d_2)
print("Element Wise Sum of arrays:\n", element_wise_sum)

Array 1:
 [[1]
 [8]
 [7]]
Array 2:
 [[6 7 1 2]]
Element Wise Sum of arrays:
 [[ 7  8  2  3]
 [14 15  9 10]
 [13 14  8  9]]


In [89]:
# Given a 3D array of shape (2, 3, 4), add a 2D array of shape (3, 4) to each 2D slice along the first axis.

array_3d = np.random.randint(1, 10, size=(2, 3, 4))
array_2d = np.random.randint(1, 10, size=(3, 4))
broadcasted_sum = array_3d + array_2d
print("Array 1:\n", array_3d)
print("Array 2:\n", array_2d)
print("Sum of arrays:\n", broadcasted_sum)

Array 1:
 [[[7 8 4 9]
  [6 3 8 9]
  [7 5 9 5]]

 [[9 3 3 2]
  [8 5 6 9]
  [1 6 5 7]]]
Array 2:
 [[1 1 2 8]
 [2 3 2 4]
 [6 9 1 4]]
Sum of arrays:
 [[[ 8  9  6 17]
  [ 8  6 10 13]
  [13 14 10  9]]

 [[10  4  5 10]
  [10  8  8 13]
  [ 7 15  6 11]]]


## Some  More

In [90]:
# Given a 2D array, use slicing to extract every second row and every second column, then add a 1D array to each row of the sliced array.

array_2d = np.random.randint(1, 10, size=(5, 5))
print("Original Array:\n", array_2d)

sliced_array = array_2d[::2, ::2]
print("Sliced Array:\n", sliced_array)

array_1d = np.array([1, 2, 3])

if sliced_array.shape[1] == array_1d.shape[0]:
    result = sliced_array + array_1d
else:
    raise ValueError("The length of the 1D array must match the number of columns in the sliced array.")

print("Result after adding 1D array:\n", result)


Original Array:
 [[5 6 7 3 9]
 [6 3 1 2 2]
 [5 6 3 7 9]
 [4 8 2 6 7]
 [3 4 8 7 1]]
Sliced Array:
 [[5 7 9]
 [5 3 9]
 [3 8 1]]
Result after adding 1D array:
 [[ 6  9 12]
 [ 6  5 12]
 [ 4 10  4]]


In [91]:
# From a 3D array of shape (4, 3, 2), extract a sub-array using slicing and then use broadcasting to subtract a 2D array from each slice along the third axis.

array_3d = np.random.randint(1, 10, size=(4, 3, 2))
print("Original 3D Array:\n", array_3d)

sub_array = array_3d[:2, :, :]
print("Sub-array:\n", sub_array)

array_2d = np.random.randint(1, 10, size=(2, 2))

result = sub_array - array_2d[:, np.newaxis]
print("Result after broadcasting subtraction:\n", result)


Original 3D Array:
 [[[9 1]
  [5 6]
  [4 3]]

 [[6 7]
  [7 6]
  [7 5]]

 [[6 5]
  [8 7]
  [1 4]]

 [[1 5]
  [9 1]
  [6 9]]]
Sub-array:
 [[[9 1]
  [5 6]
  [4 3]]

 [[6 7]
  [7 6]
  [7 5]]]
Result after broadcasting subtraction:
 [[[ 2 -7]
  [-2 -2]
  [-3 -5]]

 [[-3  6]
  [-2  5]
  [-2  4]]]


In [92]:
# Given a 2D array, extract the diagonal elements and create a 1D array.

array_2d = np.random.randint(1, 10, size=(5, 5))
diagonal_elements = np.diagonal(array_2d)
print("Original Array:\n", array_2d)
print("Diagonal Elements:\n", diagonal_elements)

Original Array:
 [[4 5 8 8 6]
 [3 4 1 8 6]
 [5 8 7 6 3]
 [8 2 5 7 2]
 [3 9 5 2 3]]
Diagonal Elements:
 [4 4 7 7 3]


In [93]:
# Use slicing to reverse the order of elements in each row of a 2D array.

array_2d = np.random.randint(1, 10, size=(5, 5))
reversed_rows = array_2d[:, ::-1]
print("Original Array:\n", array_2d)
print("Rows Reversed:\n", reversed_rows)

Original Array:
 [[3 8 8 1 4]
 [5 9 3 6 1]
 [5 8 6 5 7]
 [6 2 9 4 1]
 [1 5 2 3 5]]
Rows Reversed:
 [[4 1 8 8 3]
 [1 6 3 9 5]
 [7 5 6 8 5]
 [1 4 9 2 6]
 [5 3 2 5 1]]


In [94]:
# Given a 3D array of shape (4, 5, 6), use slicing to extract a sub-array of shape (2, 3, 4) and then use broadcasting to add a 1D array of shape (4,) to each row along the third axis.

array_3d = np.random.randint(1, 10, size=(4, 5, 6))
sub_array = array_3d[:2, :3, :4]
array_1d = np.array([1, 2, 3, 4])
result = sub_array + array_1d

print("Original 3D Array:\n", array_3d)
print("Sub-array:\n", sub_array)
print("Result after broadcasting addition:\n", result)

Original 3D Array:
 [[[4 4 3 1 4 7]
  [8 7 6 4 3 2]
  [4 4 6 6 3 6]
  [3 6 3 5 1 3]
  [6 7 5 4 4 7]]

 [[4 8 8 1 1 5]
  [3 2 1 7 8 7]
  [6 5 2 3 3 2]
  [2 3 1 2 2 6]
  [3 3 1 5 5 5]]

 [[6 2 3 5 3 4]
  [8 7 8 8 7 4]
  [6 2 8 3 9 8]
  [9 9 6 9 4 1]
  [9 6 2 6 4 1]]

 [[7 3 8 3 2 6]
  [4 8 3 6 4 3]
  [9 6 6 9 6 6]
  [8 7 3 6 7 9]
  [3 6 3 3 2 6]]]
Sub-array:
 [[[4 4 3 1]
  [8 7 6 4]
  [4 4 6 6]]

 [[4 8 8 1]
  [3 2 1 7]
  [6 5 2 3]]]
Result after broadcasting addition:
 [[[ 5  6  6  5]
  [ 9  9  9  8]
  [ 5  6  9 10]]

 [[ 5 10 11  5]
  [ 4  4  4 11]
  [ 7  7  5  7]]]


In [95]:
# Create a 2D array and use both slicing and broadcasting to set the last column to the sum of the first two columns for each row.

array_2d = np.random.randint(1, 10, size=(5, 5))
print("Original Array:\n", array_2d)

array_2d[:, -1] = array_2d[:, 0] + array_2d[:, 1]
print("Modified Array:\n", array_2d)

Original Array:
 [[9 1 6 8 1]
 [1 3 8 8 5]
 [3 3 7 5 9]
 [1 7 8 5 6]
 [1 7 4 3 2]]
Modified Array:
 [[ 9  1  6  8 10]
 [ 1  3  8  8  4]
 [ 3  3  7  5  6]
 [ 1  7  8  5  8]
 [ 1  7  4  3  8]]
